# Generated by Django 3.2.17 on 2023-03-19 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import users.models


class Migration(migrations.Migration):
    replaces = [
        ('users', '0001_initial'),
        ('users', '0002_auto_20230319_1658'),
        ('users', '0003_alter_profile_coffee_count'),
        ('users', '0004_auto_20230319_1730'),
        ('users', '0005_alter_profile_image'),
        ('users', '0006_rename_image_profile_avatar'),
        ('users', '0007_alter_profile_coffee_count'),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'birthday',
                    models.DateField(
                        blank=True,
                        help_text='дата рождения пользователя',
                        null=True,
                        verbose_name='дата рождения',
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='profile',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'coffee_count',
                    models.IntegerField(
                        default=0,
                        help_text='сколько раз пользователь пытался сварить кофе',
                        verbose_name='сварено кофе',
                    ),
                ),
                (
                    'avatar',
                    models.ImageField(
                        blank=True,
                        help_text='картинка профиля пользователя',
                        null=True,
                        upload_to=users.models.avatar_image_path,
                        verbose_name='аватарка',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Информация о пользователе',
                'verbose_name_plural': 'Информация о пользователях',
                'default_related_name': 'profile',
            },
        ),
    ]
