# Generated by Django 3.2.17 on 2023-02-19 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AbstractModel',
        ),
    ]
