# Generated by Django 3.2.17 on 2023-03-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('text', models.TextField(verbose_name='содержание')),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='дата и время создания'
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        max_length=254, verbose_name='электронная почта'
                    ),
                ),
                (
                    'status',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, 'Получено'),
                            (1, 'В обработке'),
                            (2, 'Ответ дан'),
                        ],
                        default=0,
                        verbose_name='статус обработки',
                    ),
                ),
            ],
        ),
    ]
