# Generated by Django 3.2.17 on 2023-03-19 19:51

import django.db.models.deletion
from django.db import migrations, models

import feedback.models


class Migration(migrations.Migration):
    replaces = [
        ('feedback', '0001_squashed_0002_alter_files_data'),
        ('feedback', '0002_auto_20230319_1529'),
        ('feedback', '0003_alter_feedback_text'),
        ('feedback', '0004_alter_feedback_personal_data'),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        help_text='E-mail отправителя',
                        max_length=254,
                        verbose_name='электронная почта',
                    ),
                ),
            ],
            options={
                'verbose_name': 'персональные данные автора',
                'verbose_name_plural': 'персональные данные авторов',
                'default_related_name': 'personal_data',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='дата и время создания'
                    ),
                ),
                (
                    'status',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, 'Получено'),
                            (1, 'В обработке'),
                            (2, 'Ответ дан'),
                        ],
                        default=0,
                        help_text='Статус обработки заявления',
                        verbose_name='статус обработки',
                    ),
                ),
                (
                    'text',
                    models.TextField(
                        help_text='Содержание отзыва',
                        verbose_name='содержание',
                    ),
                ),
                (
                    'personal_data',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='feedback',
                        to='feedback.personaldata',
                    ),
                ),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
                'default_related_name': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'uploaded_file',
                    models.FileField(
                        blank=True,
                        help_text='Файлы, загруженные для описания',
                        null=True,
                        upload_to=feedback.models.upload_directory_path,
                        verbose_name='загруженные файлы',
                    ),
                ),
                (
                    'data',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='files',
                        to='feedback.feedback',
                    ),
                ),
            ],
            options={
                'verbose_name': 'приложенный файл',
                'verbose_name_plural': 'приложенные файлы',
                'default_related_name': 'files',
            },
        ),
    ]
