# Generated by Django 3.2.17 on 2023-02-19 18:53

import catalog.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.TextField(
                        help_text='Добавьте название товара',
                        max_length=150,
                        verbose_name='Название',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True,
                        help_text='Выберите статус..',
                        verbose_name='Опубликовать?',
                    ),
                ),
                (
                    'slug',
                    models.TextField(
                        help_text='Добавьте код для url',
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                '^[0-9a-zA-Z-_]*$',
                                'Использовать можно только цифры, буквы латиницы и `-`, `_`',
                            )
                        ],
                        verbose_name='Символьный код для url',
                    ),
                ),
                (
                    'weight',
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text='Введите вес',
                        verbose_name='Вес',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.TextField(
                        help_text='Добавьте название товара',
                        max_length=150,
                        verbose_name='Название',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True,
                        help_text='Выберите статус..',
                        verbose_name='Опубликовать?',
                    ),
                ),
                (
                    'slug',
                    models.TextField(
                        help_text='Добавьте код для url',
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                '^[0-9a-zA-Z-_]*$',
                                'Использовать можно только цифры, буквы латиницы и `-`, `_`',
                            )
                        ],
                        verbose_name='Символьный код для url',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.TextField(
                        help_text='Добавьте название товара',
                        max_length=150,
                        verbose_name='Название',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True,
                        help_text='Выберите статус..',
                        verbose_name='Опубликовать?',
                    ),
                ),
                (
                    'text',
                    models.TextField(
                        help_text='Добавьте описание',
                        validators=[
                            catalog.validators.ValidateMustContain(
                                'превосходно', 'роскошно'
                            )
                        ],
                        verbose_name='Описание',
                    ),
                ),
                (
                    'catalog_category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='catalog.category',
                        verbose_name='Категория',
                    ),
                ),
                (
                    'tag',
                    models.ManyToManyField(
                        related_name='items',
                        to='catalog.Tag',
                        verbose_name='Тег',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
