# Generated by Django 3.2.17 on 2023-02-21 16:22

import re

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import catalog.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True,
                        help_text='Выберите статус публикации',
                        verbose_name='опубликовать?',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Добавьте название товара',
                        max_length=150,
                        unique=True,
                        verbose_name='название',
                    ),
                ),
                (
                    'slug',
                    models.CharField(
                        help_text='Напишите код для url(латинские буквы, цифры и `-`, `_`)',
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile('^[-a-zA-Z0-9_]+\\Z'),
                                'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.',
                                'invalid',
                            )
                        ],
                        verbose_name='слаг',
                    ),
                ),
                (
                    'weight',
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text='Введите вес(число 0-100)',
                        verbose_name='вес',
                    ),
                ),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True,
                        help_text='Выберите статус публикации',
                        verbose_name='опубликовать?',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Добавьте название товара',
                        max_length=150,
                        unique=True,
                        verbose_name='название',
                    ),
                ),
                (
                    'slug',
                    models.CharField(
                        help_text='Напишите код для url(латинские буквы, цифры и `-`, `_`)',
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile('^[-a-zA-Z0-9_]+\\Z'),
                                'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.',
                                'invalid',
                            )
                        ],
                        verbose_name='слаг',
                    ),
                ),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True,
                        help_text='Выберите статус публикации',
                        verbose_name='опубликовать?',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Добавьте название товара',
                        max_length=150,
                        unique=True,
                        verbose_name='название',
                    ),
                ),
                (
                    'text',
                    models.TextField(
                        help_text='Описание(>2 символов, содержит "превосходно, роскошно")',
                        validators=[
                            catalog.validators.ValidateMustContain(
                                'превосходно', 'роскошно'
                            )
                        ],
                        verbose_name='описание',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='catalog.category',
                        verbose_name='категория',
                    ),
                ),
                (
                    'tags',
                    models.ManyToManyField(
                        related_name='items',
                        to='catalog.Tag',
                        verbose_name='тег',
                    ),
                ),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'default_related_name': 'items',
            },
        ),
    ]
