# Generated by Django 3.2.17 on 2023-02-21 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.PositiveSmallIntegerField(
                default=100,
                help_text='Введите вес(число 0-100)',
                validators=[django.core.validators.MaxValueValidator(32767)],
                verbose_name='вес',
            ),
        ),
    ]
