# Generated by Django 3.2.17 on 2023-03-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0001_squashed_0003_auto_20230307_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='дата добавления товара'
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True, verbose_name='дата изменения товара'
            ),
        ),
    ]
