# Generated by Django 3.2.17 on 2023-02-26 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0001_squashed_0003_auto_20230223_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMainImages',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        help_text='загрузите картинки для уточнения описания',
                        upload_to='media/uploaded',
                        verbose_name='изображение(будет масштабировано до 300x300)',
                    ),
                ),
            ],
            options={
                'default_related_name': 'main_image',
            },
        ),
        migrations.CreateModel(
            name='ItemDescriptionsImages',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        help_text='загрузите картинки для уточнения описания',
                        upload_to='media/uploaded',
                        verbose_name='изображение(будет масштабировано до 300x300)',
                    ),
                ),
                (
                    'item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='description_images',
                        to='catalog.item',
                        verbose_name='галерея изображений товара',
                    ),
                ),
            ],
            options={
                'default_related_name': 'description_images',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='main_image',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='item',
                to='catalog.itemmainimages',
                verbose_name='главное фото',
            ),
        ),
    ]
