# Generated by Django 3.2.17 on 2023-02-19 20:07

import catalog.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.TextField(
                help_text='Напишите код для url(только лат. буквы, цифры и `-`, `_`)',
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        '^[0-9a-zA-Z-_]*$',
                        'Использовать можно только цифры, буквы латиницы и `-`, `_`',
                    )
                ],
                verbose_name='Символьный код для url',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.PositiveSmallIntegerField(
                default=100,
                help_text='Введите вес(число 0-100)',
                verbose_name='Вес',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(
                help_text='Описание(>2 символов, содержит "превосходно, роскошно")',
                validators=[
                    catalog.validators.ValidateMustContain(
                        'превосходно', 'роскошно'
                    ),
                    django.core.validators.MinLengthValidator(2),
                ],
                verbose_name='Описание',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.TextField(
                help_text='Напишите код для url(только лат. буквы, цифры и `-`, `_`)',
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        '^[0-9a-zA-Z-_]*$',
                        'Использовать можно только цифры, буквы латиницы и `-`, `_`',
                    )
                ],
                verbose_name='Символьный код для url',
            ),
        ),
    ]
