# Generated by Django 3.2.17 on 2023-02-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0002_alter_category_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='unique_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
