# Generated by Django 3.2.17 on 2023-02-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0002_auto_20230226_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdescriptionsimages',
            name='image',
            field=models.ImageField(
                help_text='загрузите картинки для уточнения описания',
                upload_to='uploaded',
                verbose_name='изображение(будет масштабировано до 300x300)',
            ),
        ),
        migrations.AlterField(
            model_name='itemmainimages',
            name='image',
            field=models.ImageField(
                help_text='загрузите картинки для уточнения описания',
                upload_to='uploaded',
                verbose_name='изображение(будет масштабировано до 300x300)',
            ),
        ),
    ]
