# Generated by Django 3.2.17 on 2023-02-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0003_alter_item_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesUniqueNames',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.TextField(max_length=150, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TagsUniqueNames',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.TextField(max_length=150, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
