# Generated by Django 3.2.17 on 2023-02-26 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0003_auto_20230226_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMainImage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        help_text='загрузите картинки для уточнения описания',
                        upload_to='uploaded',
                        verbose_name='изображение(будет масштабировано до 300x300)',
                    ),
                ),
            ],
            options={
                'default_related_name': 'main_image',
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='main_image',
        ),
        migrations.DeleteModel(
            name='ItemMainImages',
        ),
        migrations.AddField(
            model_name='itemmainimage',
            name='item',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='main_image',
                to='catalog.item',
                verbose_name='главное фото',
            ),
        ),
    ]
