# Generated by Django 3.2.17 on 2023-02-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0004_alter_category_unique_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(
                help_text='Добавьте название',
                max_length=150,
                unique=True,
                verbose_name='название',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(
                help_text='Добавьте название',
                max_length=150,
                unique=True,
                verbose_name='название',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(
                help_text='Добавьте название',
                max_length=150,
                unique=True,
                verbose_name='название',
            ),
        ),
    ]
