# Generated by Django 3.2.17 on 2023-02-20 20:30

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20230220_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Выберите статус..', verbose_name='опубликовать?'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(help_text='Добавьте название товара', max_length=150, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.PositiveSmallIntegerField(default=100, help_text='Введите вес(число 0-100)', verbose_name='вес'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Выберите статус..', verbose_name='опубликовать?'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.TextField(help_text='Добавьте название товара', max_length=150, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(help_text='Описание(>2 символов, содержит "превосходно, роскошно")', validators=[catalog.validators.ValidateMustContain('превосходно', 'роскошно')], verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Выберите статус..', verbose_name='опубликовать?'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.TextField(help_text='Добавьте название товара', max_length=150, verbose_name='название'),
        ),
    ]
