# Generated by Django 3.2.17 on 2023-02-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0007_auto_20230221_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='unique_name',
            field=models.CharField(
                editable=False, max_length=150, unique=True
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='unique_name',
            field=models.CharField(
                editable=False, max_length=150, unique=True
            ),
        ),
    ]
