name: Testing

on:
  push:
    branches: [ "main", "develop", "feature/1", "feature/2", "feature/3" ]
  pull_request:
    branches: [ "main", "develop", "feature/1", "feature/2", "feature/3" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/basic-requirements.txt
        pip install django-debug-toolbar==3.8.1
        pip install django-dump-load-utf8==0.0.4
        pip install mock==5.0.1
    - name: Run Tests
      run: |
        python manage.py test
